# Generated by Django 4.0.5 on 2022-07-09 15:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='devices',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)])),
                ('route_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('carbon_mono', models.FloatField()),
                ('light', models.FloatField()),
                ('noise', models.FloatField()),
                ('langitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.devices')),
            ],
        ),
    ]
