# Generated by Django 4.0.5 on 2022-07-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensors',
            name='sensor_id',
        ),
        migrations.DeleteModel(
            name='devices',
        ),
        migrations.DeleteModel(
            name='sensors',
        ),
    ]
